# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py312

[flake8]
ignore = D203,C901
exclude = .git,__pycache__,docs/source/conf.py,old,build,dist,site-packages,venv,bin
max-complexity = 12
max-line-length = 120

[testenv]
setenv =
    GDAL_MEM_ENABLE_OPEN = YES
basepython = python3.12
envdir = venv
sitepackages = True
extras =
  test
allowlist_externals =
  flake8
  pytest
commands =
    flake8
    pytest
