name: build_tox_tests

on: [push]

jobs:
  tox_in_docker:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          path: hls-testing_dat
          repository: NASA-IMPACT/hls-testing_data

      - name: Build container and run Tox tests in container
        run: scripts/test
