name: build_tox_tests

on: [push]

jobs:
  build_push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --tag hls_hdf_to_cog

      - name: Tox tests in container
        run: docker run hls_hdf_to_cog
